### PR TITLE
Add double quotes for PATH variable

### PR DESCRIPTION
**Pull request by escalate**
Use the same style like the official documentation does

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
@escalate

Thank you for your PR!
Your change is good, but I ask you two modifications.

1. Change the commit message's title to `fix: add double quotes for PATH variable`
2. Add the line `regexp: '^\s*export\s*PATH="?\$PYENV_ROOT/bin:\$PATH"?'` to prevent the duplication

The commit message format of this project conforms to the [AngularJS Commit Message Format](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format).
By conforming its format, we can generate the [Change Log](CHANGELOG.md) and conform the [semantic versioning](http://semver.org/) automatically by [standard-version](https://www.npmjs.com/package/standard-version).
We validate the commit message with git's `commit-msg` hook using [validate-commit-msg](https://www.npmjs.com/package/validate-commit-msg) and [husky](https://www.npmjs.com/package/husky).

I have made the [Contributing Guide Line](https://github.com/suzuki-shunsuke/ansible-pyenv/CONTRIBUTING.md), so please read it.


Best regards.

**Comment by escalate** [comment]
@suzuki-shunsuke  I changed the commit message but I don't understand your 2nd point. Should I add this to the commit message or should I put this into task.yml?

**Comment by suzuki-shunsuke** [comment]
@escalate 

Thank you!
I will merge this PR and release the new version.

**Comment by suzuki-shunsuke** [comment]
@escalate 
I have released the version 3.2.4 .

* https://github.com/suzuki-shunsuke/ansible-pyenv/releases/tag/v3.2.4
* https://github.com/suzuki-shunsuke/ansible-pyenv/blob/master/CHANGELOG.md

Best regards.

**Pull request merged**
